info:
  name: Delete Role
  type: http
  seq: 7

http:
  method: DELETE
  url: "{{baseUrl}}/api/admin/roles/{id}"
  headers:
    - name: Authorization
      value: Bearer {{token}}
  auth: inherit

settings:
  encodeUrl: true
  timeout: 0
  followRedirects: true
  maxRedirects: 5
